Fix non-SSML pauses with libsonic
espeak-ng/espeak-ng pull request #1526
Opened 2022-11-11 19:36 UTC by djphoenix

Following #1512 

I unfortunately have broken in-speech pauses by fixing ones that should be constant-time.
This PR adds a back-compensation (again) for pauses that should be calculated at speech rate.

2022-11-11 20:03 UTC, jaacoppi requested changes
The PR is okay. 

I'm asking for some extra cleanup and refactoring because you now have studied this part of the code and currently understand and remember how it works..

1) Most variables in that function seem to be called *_factor. Could the _factor part be removed from all of those? is it a good idea?

2) We have 3 variable names that are easy to mix up with each other:
int pause_factor;
int wav_pause_factor;
int wav_factor;

Can you think of a better naming convention? Would be great if we can separate the variables more clearly. That way the code would be self-documenting.

2022-11-11 20:26 UTC, djphoenix commented
@jaacoppi this PR are in progress now again. I have found that speed is lower twice than original behavior. Now I inspecting spectrograms to find a root difference cause.

2022-11-11 21:11 UTC, djphoenix commented
I have reverted change that breaks sonic speech, and add a compensation directly to SSML code. This is how it should be done is the beginning.

2022-11-11 21:20 UTC, djphoenix commented
@jaacoppi CI is happy, please review again

2022-11-12 05:29 UTC, jaacoppi requested changes
1) Commented code should be removed:
+                               // if (voice->speed_percent > 0)
+                               //      wpm = (wpm * voice->speed_percent)/100;


2) Without testing it myself it looks like this part could be made simpler:
+                               int wpm2 = wpm;
+                               wpm = espeakRATE_NORMAL;
+                               double sonic = ((double)wpm2)/wpm;
+                               value2 = value2 * sonic;

How about removing wpm2 like this:
+                               double sonic = ((double)wpm)/espeakRATE_NORMAL;
+                               value2 = value2 * sonic;

2022-11-12 08:06 UTC, jaacoppi approved these changes

2022-11-12 08:06 UTC, merged