Rework CI
espeak-ng/espeak-ng pull request #1539
Opened 2022-11-17 17:16 UTC by djphoenix

- Add more compilers - especially GCC on macOS and Clang.
- Add more architectures - especially RISC-V-64
- Move build outside of QEMU (use cross-compilation)
- Use qemu-user for test on target environment
- Add Android CI with APK artifacts

2022-11-17 17:23 UTC, djphoenix commented
Oh... on my fork, ubuntu-latest was a jammy, and here I see a focal. And no gcc-12 here. What..?

2022-11-17 18:35 UTC, djphoenix commented
aarch64 with thread sanitizer takes too long... Should we keep it here?

2022-11-17 19:42 UTC, alex19EP requested changes
some minor nitpicking from me.

2022-11-17 19:42 UTC, alex19EP commented on .github/workflows/ci.yml
> +          # Vangrind is unavailable for cross-builds
should it be:
```suggestion
          # Valgrind is unavailable for cross-builds
```

2022-11-17 19:42 UTC, alex19EP commented on .github/workflows/dist.yml
> +name: Distributes
maybe shorten it to:

```suggestion
name: Dist
```

2022-11-18 17:47 UTC, alex19EP approved these changes
LGTM

2022-11-19 13:31 UTC, djphoenix commented
@jaacoppi @sthibaul any comments?

2022-11-19 13:42 UTC, sthibaul commented
LGTM as well, thanks!

2022-11-19 14:17 UTC, merged